version: "3.9"

services:

  db:
    container_name: db
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_DATABASE: db
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - ./.db:/var/lib/mysql
    expose:
      - 3306
      - 33060

  adminer:
    container_name: adminer
    image: adminer:latest
    restart: always
    ports:
      - 8080:8080
    depends_on:
      - db

  backend:
    container_name: backend
    image: full-stack-challenge-backend
    build:
      context: .
      dockerfile: Dockerfile-backend
    restart: always
    command: bash -c "
        cd backend && composer install && php artisan vendor:publish --tag=request-docs-config &&
        php artisan optimize:clear && php artisan lrd:generate &&
        php artisan migrate && php artisan serve --host=0.0.0.0"
    ports:
      - 8000:8000
    volumes:
      - ./backend:/backend
    depends_on:
      - db

  frontend:
    container_name: full-stack-challenge-frontend
    image: node:lts
    command: bash -c "cd frontend && npm i && npm start"
    ports:
      - 4200:4200
    volumes:
      - ./frontend:/frontend
    depends_on:
      - backend
